-- Verification fixture. NOT part of any pipeline run.
--
-- The transformation is built before the extract task that feeds it exists, so
-- something has to create and populate the landing table in order to verify the
-- models at all. This is that something, and nothing else.
--
-- It is deliberately outside every path dbt reads, and no model or macro
-- references it. Once CH3's extract exists, the extract fills this table with
-- real rows copied from source_db and this file stays only as a way to exercise
-- the models on their own.
--
-- Rows are generated by construction rather than randomly, so the fixture is
-- reproducible without needing a seed.
--
-- Run:  docker compose exec -T postgres psql -U "$POSTGRES_USER" -d warehouse_db < dbt/fixtures/raw_customers.sql
--
-- See adr/0007-split-the-landing-table-contract-from-its-population.md

CREATE SCHEMA IF NOT EXISTS raw;

-- CASCADE is required once the transformation has run at least once: the
-- staging view is built on this table and blocks a plain DROP. The pipeline's
-- extract step drops it the same way, for the same reason. dbt recreates the
-- view on the next run.
DROP TABLE IF EXISTS raw.customers CASCADE;

-- Column names and types mirror the upstream table in source_db, because the
-- extract copies it verbatim. Anything different here would verify the models
-- against a shape the real pipeline never produces.
CREATE TABLE raw.customers (
    customer_id BIGINT  PRIMARY KEY,
    first_name  TEXT    NOT NULL,
    last_name   TEXT    NOT NULL,
    email       TEXT    NOT NULL,
    country     TEXT    NOT NULL,
    signup_date DATE    NOT NULL,
    is_active   BOOLEAN NOT NULL
);

COMMENT ON TABLE raw.customers IS
    'Landing table. Filled by the pipeline''s extract step; this fixture stands in while verifying the transformation on its own.';

INSERT INTO raw.customers (
    customer_id, first_name, last_name, email, country, signup_date, is_active
)
SELECT
    i,
    first_names.name,
    last_names.name,
    lower(first_names.name) || '.' || lower(last_names.name) || i || '@example.com',
    countries.code,
    DATE '2023-01-01' + ((i * 7) % 1000),
    (i % 5) <> 0
FROM generate_series(1, 500) AS i
CROSS JOIN LATERAL (
    SELECT (ARRAY['Elif', 'Deniz', 'Mert', 'Anna', 'Lukas', 'Sofia', 'Yuki', 'Priya'])[(i % 8) + 1] AS name
) AS first_names
CROSS JOIN LATERAL (
    SELECT (ARRAY['Yilmaz', 'Kaya', 'Demir', 'Novak', 'Rossi', 'Silva', 'Tanaka', 'Sharma'])[(i % 8) + 1] AS name
) AS last_names
CROSS JOIN LATERAL (
    SELECT (ARRAY['TR', 'DE', 'NL', 'GB', 'JP', 'IN'])[(i % 6) + 1] AS code
) AS countries;
