"""Keep the simulated upstream system operating.

Appends a batch of new customer records on a fixed interval, so the pipeline has
changing work to do rather than reprocessing an identical table forever. Records
are generated by identifier, so the source's contents stay a function of how
many intervals have elapsed.

This represents the world outside the pipeline. It only ever writes to the
source, never to the warehouse and never to the transformation project.

See adr/0012-let-the-simulated-upstream-keep-operating.md
"""

from __future__ import annotations

import sys
import time

from customer_rows import build_csv
from db import connect, copy_rows, identifier_column, max_identifier, require_env, row_count


def append_batch(batch_size: int, random_seed: int) -> tuple[int, str]:
    """Append one batch of arrivals; report the row count and the identifier used."""
    connection = connect()
    try:
        identifier = identifier_column(connection)
        first_id = max_identifier(connection) + 1
        last_id = first_id + batch_size - 1
        copy_rows(connection, build_csv(first_id, last_id, random_seed))
        return row_count(connection), identifier
    finally:
        connection.close()


def main() -> int:
    batch_size = int(require_env("ARRIVAL_BATCH_SIZE"))
    interval_seconds = int(require_env("ARRIVAL_INTERVAL_SECONDS"))
    random_seed = int(require_env("SEED_RANDOM_SEED"))

    print(
        f"upstream activity: {batch_size} records every {interval_seconds}s, "
        f"seed {random_seed}"
    )

    # Reported so an operator can see, during the demo, that the upstream
    # migrated its own schema rather than stalling on it.
    last_identifier = ""

    while True:
        time.sleep(interval_seconds)
        total, identifier = append_batch(batch_size, random_seed)
        if last_identifier and identifier != last_identifier:
            print(
                f"upstream renamed its identifier: {last_identifier} -> {identifier}; "
                f"following it"
            )
        last_identifier = identifier
        print(f"{batch_size} customers arrived; source now holds {total}")


if __name__ == "__main__":
    sys.exit(main())
